#
# push時に特定のソースファイルを追加してcommitしてmergeする
#
name: Additional commit

on:
  push:
    branches:
      - master
    paths:
      - date.txt

jobs:
  fetch_source:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup git
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: switch branch
        run: |
          git fetch
          git switch additional || git switch -c additional

      - name: merge master
        run: git merge --allow-unrelated-histories --no-ff -X theirs -m "[Merge] catch up (automated)" master

      - name: add file, commit, and push
        run: |
          date>date.txt
          git clone --depth=1 https://github.com/lua/lua
          git add -f lua
          git add date.txt
          git commit -m "[Modify] date (automated) [no ci]"
          git push origin additional
