name: confirm cmake help

on: push

jobs:
  cmake_help:
    if: contains(github.event.head_commit.message, 'cmake-help')
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: show CMake help on ${{ matrix.os }}
        run: cmake --help
