#
# GitHub CLI経由でAPIを呼ぶ
#
name: invoke GitHub API using GitHub CLI

on: push

jobs:
  invoke_api:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the workflow was called from master branch
        run: |
          gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/$REPOSITORY/releases/latest
        env:
          REPOSITORY: Enchan1207/rpi-buildroot
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
