#
# 手動実行ワークフロー
#
name: manual workflow

on:
  workflow_dispatch:

jobs:
  branch-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check if the workflow was called from master branch
        run: |
          CURRENT=`git branch | grep "^*" | sed -e "s/^\* //"`
          CHECK="master"
          [ $CURRENT = $CHECK ]

  echoback:
    needs: branch-check
    runs-on: ubuntu-latest

    steps:
      - name: echoback
        run: echo "Hello from master branch!"
