#
# イメージ作成
#
name: push image

on: push

env:
  IMAGE_NAME: test_mini_image

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: build docker container
        run: docker build -t $IMAGE_NAME -f test.Dockerfile .

      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build image and push to registry
        uses: docker/build-push-action@v5
        with:
          push: true
          file: test.Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest
