#
# リリース時に走るワークフロー
#

name: release information

on:
  release:
    types:
      - released

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Show release ref
        run: echo "Release ref;${{ github.ref }}"
