#
# 自分自身をアクションとして呼び出す
#

on: push

jobs:
  self_invocation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: Enchan1207/gha-sandbox@master
        with:
          config_file: README.md

      - name: check files
        run: |
          pwd
          ls -la
          cd dir_by_action
          ls -la
